import { Inter } from "next/font/google";

import ClientQueryProvider from "@/providers/ClientQueryProvider";

import type { Metadata } from "next";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientQueryProvider>{children}</ClientQueryProvider>
      </body>
    </html>
  );
}
